### ISSUE TITLE
Text size

### ISSUE THREAD

**Issue by Eusorph** [michaellw/Obsidian-Canvas-Style-Menu#7]
Also, it would be awesome to have a command that changes the text size of the whole note.

**Comment by michaellw** [comment]
Hello, this can be done by adding custom css, you can refer to the following way to add custom font styles and canvas menu buttons:
Step1: add these css snippets to your custom css:
```css
.canvas-node.canvas-font-small .markdown-preview-sizer {
  font-size: small;
}
.canvas-node.canvas-font-medium .markdown-preview-sizer {
  font-size: medium;
}
.canvas-node.canvas-font-large .markdown-preview-sizer {
  font-size: large;
}
```
Step2: Adding menu buttons in plugin settings:
![image](https://github.com/michaellw/Obsidian-Canvas-Style-Menu/assets/276357/18bf8e04-1a59-4abb-a1d3-230bdce2d3e4)
Step3: Using the canvas menu
![image](https://github.com/michaellw/Obsidian-Canvas-Style-Menu/assets/276357/3f93cc3a-f71a-4d33-906d-7469fe526740)
